version = 0.1
[default.deploy.parameters]
stack_name = "thumbnail"
resolve_s3 = true
s3_prefix = "thumbnail"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketNameParam=\"my-super-secret-unique-bucket\""
image_repositories = []
